"""The ring Z[1/60] — fractions with 5-smooth denominators.

This is the natural number system for sexagesimal computation:
every element has a terminating base-60 expansion.

Z[1/60] is a subring of Q containing Z. It's the localization of Z
at the multiplicative set generated by {2, 3, 5}.

Properties:
- Z[1/60] is a principal ideal domain
- Its units are { ±2^a × 3^b × 5^c : a,b,c ∈ Z }
- Its primes are all primes ≥ 7 (2, 3, 5 become units)
- Factorization in Z[1/60] is unique
"""

from __future__ import annotations

from fractions import Fraction
from functools import total_ordering
from math import gcd

from cuneiform.core.smooth import is_smooth, extract_smooth_part, smooth_exponents
from cuneiform.number_theory.primes import is_prime


@total_ordering
class SmoothRing:
    """An element of Z[1/60] = { a/b : b is 5-smooth }.

    Stored as (numerator, smooth_exponents) where the denominator
    is 2^e0 × 3^e1 × 5^e2.
    """

    __slots__ = ("num", "exp")

    def __init__(self, numerator: int = 0,
                 smooth_exponents: tuple[int, int, int] = (0, 0, 0)):
        self.num = numerator
        self.exp = smooth_exponents
        self._normalize()

    def _normalize(self):
        """Cancel common factors between numerator and denominator."""
        if self.num == 0:
            self.exp = (0, 0, 0)
            return
        e0, e1, e2 = self.exp
        # Cancel factors of 2
        while e0 > 0 and self.num % 2 == 0:
            self.num //= 2
            e0 -= 1
        # Cancel factors of 3
        while e1 > 0 and self.num % 3 == 0:
            self.num //= 3
            e1 -= 1
        # Cancel factors of 5
        while e2 > 0 and self.num % 5 == 0:
            self.num //= 5
            e2 -= 1
        self.exp = (e0, e1, e2)

    @classmethod
    def from_int(cls, n: int) -> SmoothRing:
        return cls(n, (0, 0, 0))

    @classmethod
    def from_fraction(cls, num: int, den: int) -> SmoothRing:
        """Create from numerator/denominator. Raises if den is not 5-smooth."""
        if den < 0:
            num, den = -num, -den
        if den == 0:
            raise ZeroDivisionError("Denominator cannot be zero")
        exp = smooth_exponents(den)
        if exp is None:
            raise ValueError(f"Denominator {den} is not 5-smooth; "
                             f"not an element of Z[1/60]")
        return cls(num, exp)

    @classmethod
    def from_rational(cls, f: Fraction) -> SmoothRing:
        """Create from a Fraction. Raises if denominator is not 5-smooth."""
        return cls.from_fraction(f.numerator, f.denominator)

    @property
    def denominator(self) -> int:
        return (2 ** self.exp[0]) * (3 ** self.exp[1]) * (5 ** self.exp[2])

    @property
    def as_fraction(self) -> Fraction:
        return Fraction(self.num, self.denominator)

    @property
    def is_integer(self) -> bool:
        return self.exp == (0, 0, 0)

    @property
    def is_unit(self) -> bool:
        """Units in Z[1/60] are ± products of powers of 2, 3, 5."""
        if self.num == 0:
            return False
        return is_smooth(abs(self.num))

    @property
    def is_zero(self) -> bool:
        return self.num == 0

    @property
    def irregular_part(self) -> int:
        """The cofactor after removing all factors of 2, 3, 5 from numerator.

        This is the "hard" part in Z[1/60] — the part that isn't a unit.
        """
        if self.num == 0:
            return 0
        _, cofactor = extract_smooth_part(abs(self.num))
        return cofactor

    @property
    def smooth_factorization(self) -> tuple[int, int]:
        """Factor numerator into (smooth_part, cofactor).

        numerator = smooth_part * cofactor where cofactor has no {2,3,5} factors.
        """
        if self.num == 0:
            return (0, 0)
        return extract_smooth_part(abs(self.num))

    def is_prime_in_ring(self) -> bool:
        """Is self prime in Z[1/60]?

        True iff |numerator| is a prime ≥ 7 (times a unit denominator).
        Primes 2, 3, 5 are units in this ring, not primes.
        """
        if self.num == 0:
            return False
        _, cofactor = extract_smooth_part(abs(self.num))
        return cofactor > 1 and is_prime(cofactor)

    def __add__(self, other: SmoothRing) -> SmoothRing:
        f = self.as_fraction + other.as_fraction
        return SmoothRing.from_rational(f)

    def __sub__(self, other: SmoothRing) -> SmoothRing:
        f = self.as_fraction - other.as_fraction
        return SmoothRing.from_rational(f)

    def __mul__(self, other: SmoothRing) -> SmoothRing:
        new_num = self.num * other.num
        new_exp = (
            self.exp[0] + other.exp[0],
            self.exp[1] + other.exp[1],
            self.exp[2] + other.exp[2],
        )
        return SmoothRing(new_num, new_exp)

    def __truediv__(self, other: SmoothRing) -> SmoothRing:
        """Division in Z[1/60].

        Always exact if other is a unit (5-smooth).
        For non-unit divisors: computes the quotient in Q and checks
        that the result is in Z[1/60].
        """
        if other.num == 0:
            raise ZeroDivisionError("Division by zero in Z[1/60]")
        f = self.as_fraction / other.as_fraction
        return SmoothRing.from_rational(f)

    def __neg__(self) -> SmoothRing:
        return SmoothRing(-self.num, self.exp)

    def __abs__(self) -> SmoothRing:
        return SmoothRing(abs(self.num), self.exp)

    def __eq__(self, other: object) -> bool:
        if isinstance(other, SmoothRing):
            return self.as_fraction == other.as_fraction
        if isinstance(other, int):
            return self.as_fraction == Fraction(other)
        return NotImplemented

    def __lt__(self, other: SmoothRing) -> bool:
        return self.as_fraction < other.as_fraction

    def __hash__(self) -> int:
        return hash(self.as_fraction)

    def __bool__(self) -> bool:
        return self.num != 0

    def __repr__(self) -> str:
        if self.exp == (0, 0, 0):
            return f"Z60({self.num})"
        den = self.denominator
        return f"Z60({self.num}/{den})"

    def __str__(self) -> str:
        if self.exp == (0, 0, 0):
            return str(self.num)
        return f"{self.num}/{self.denominator}"


def ring_primes_up_to(n: int) -> list[SmoothRing]:
    """All primes of Z[1/60] up to n (i.e., primes ≥ 7)."""
    result = []
    for k in range(7, n + 1):
        if is_prime(k):
            result.append(SmoothRing.from_int(k))
    return result


def ring_units_up_to(n: int) -> list[SmoothRing]:
    """All positive units of Z[1/60] up to n (i.e., 5-smooth numbers)."""
    from cuneiform.core.smooth import generate_smooth_numbers
    return [SmoothRing.from_int(s.value) for s in generate_smooth_numbers(n)]
