"""Babylonian reciprocal pairs & modular extension.

Reciprocal pairs were THE fundamental operation in Old Babylonian mathematics.
Extended here into modular arithmetic for crypto-relevant analysis.
"""

from __future__ import annotations

from fractions import Fraction
from math import gcd

from cuneiform.core.rational import SexaRational
from .regularity import RegularityClass, classify_regularity


class ReciprocalPair:
    """A Babylonian reciprocal pair (x, x_bar) where x * x_bar = 1.

    In OB math, pairs satisfy x * x_bar = 60^k. We normalize so product = 1.
    """

    __slots__ = ("x", "x_bar")

    def __init__(self, x: SexaRational | int):
        if isinstance(x, int):
            x = SexaRational(x)
        if x == SexaRational(0):
            raise ValueError("Cannot form reciprocal pair with zero")
        self.x = x
        self.x_bar = SexaRational(1) / x

    @property
    def sum(self) -> SexaRational:
        """x + x_bar -- the diagonal generator."""
        return self.x + self.x_bar

    @property
    def difference(self) -> SexaRational:
        """x - x_bar -- the width generator."""
        return self.x - self.x_bar

    @property
    def pythagorean_triple(self) -> tuple[int, int, int] | None:
        """The Pythagorean triple generated by this pair.

        width = (x - x_bar) / 2, length = 1 (normalized), diag = (x + x_bar) / 2
        Scaled to integers. Returns None if not integer-scalable.
        """
        half_diff = self.difference / SexaRational(2)
        half_sum = self.sum / SexaRational(2)

        # Find scaling factor to make all integers
        d1 = half_diff.as_fraction.denominator
        d2 = half_sum.as_fraction.denominator
        # lcm of denominators
        scale = (d1 * d2) // gcd(d1, d2)

        w = int((half_diff * SexaRational(scale)).as_fraction)
        l = scale
        d = int((half_sum * SexaRational(scale)).as_fraction)

        if w <= 0:
            return None
        # Simplify by gcd
        g = gcd(gcd(abs(w), l), abs(d))
        return (abs(w) // g, l // g, abs(d) // g)

    def compose(self, other: ReciprocalPair) -> ReciprocalPair:
        """Composition: (x*y, x_bar*y_bar) is also a pair."""
        return ReciprocalPair(self.x * other.x)

    def power(self, n: int) -> ReciprocalPair:
        """Repeated composition: (x^n, x_bar^n)."""
        return ReciprocalPair(self.x ** n)

    def __repr__(self) -> str:
        return f"RP({self.x}, {self.x_bar})"

    def __eq__(self, other: object) -> bool:
        if isinstance(other, ReciprocalPair):
            return self.x == other.x
        return NotImplemented


class ModularReciprocalPair:
    """Reciprocal pairs in modular arithmetic.

    (x, x^-1 mod n) with regularity classification of both values.
    """

    __slots__ = ("x", "n", "x_inv", "_rc_x", "_rc_inv")

    def __init__(self, x: int, modulus: int):
        self.x = x % modulus
        self.n = modulus
        if gcd(x, modulus) != 1:
            self.x_inv = None
        else:
            self.x_inv = pow(x, -1, modulus)
        self._rc_x = None
        self._rc_inv = None

    @property
    def is_valid(self) -> bool:
        return self.x_inv is not None

    @property
    def regularity_x(self) -> dict:
        if self._rc_x is None and self.x > 0:
            self._rc_x = classify_regularity(self.x)
        return self._rc_x

    @property
    def regularity_x_inv(self) -> dict:
        if self._rc_inv is None and self.x_inv is not None and self.x_inv > 0:
            self._rc_inv = classify_regularity(self.x_inv)
        return self._rc_inv

    @property
    def pair_regularity(self) -> int:
        """Max of largest prime factors of x and x_inv. Lower = more regular."""
        if not self.is_valid:
            return float("inf")
        r_x = self.regularity_x.get("largest_prime_factor", 999)
        r_inv = self.regularity_x_inv.get("largest_prime_factor", 999)
        return max(r_x, r_inv)

    @property
    def sum_mod(self) -> int:
        """(x + x^-1) mod n."""
        if not self.is_valid:
            return 0
        return (self.x + self.x_inv) % self.n

    @property
    def difference_mod(self) -> int:
        """(x - x^-1) mod n."""
        if not self.is_valid:
            return 0
        return (self.x - self.x_inv) % self.n

    def __repr__(self) -> str:
        return f"MRP({self.x}, {self.x_inv}, mod {self.n})"


class ReciprocalTable:
    """Babylonian reciprocal table extended to modular arithmetic.

    Organized by regularity class — the novel contribution.
    """

    def __init__(self, modulus: int, max_value: int | None = None):
        self.n = modulus
        self.max_val = max_value or modulus
        self.pairs: dict[int, ModularReciprocalPair] = {}
        self.by_regularity: dict[int, list[ModularReciprocalPair]] = {}

    def build(self) -> None:
        """Construct the full reciprocal table mod n."""
        for x in range(1, self.max_val):
            if gcd(x, self.n) != 1:
                continue
            pair = ModularReciprocalPair(x, self.n)
            if not pair.is_valid:
                continue
            self.pairs[x] = pair
            rc = pair.pair_regularity
            if rc not in self.by_regularity:
                self.by_regularity[rc] = []
            self.by_regularity[rc].append(pair)

    def regular_pairs(self, max_prime: int = 5) -> list[ModularReciprocalPair]:
        """Pairs where both x and x^-1 have largest prime factor <= max_prime."""
        return [p for p in self.pairs.values() if p.pair_regularity <= max_prime]

    def smooth_sum_rate(self, smoothness_bound: int) -> dict[int, float]:
        """Fraction of reciprocal pair sums that are B-smooth, by regularity class.

        THE KEY EXPERIMENT: if higher-regularity pairs produce smooth sums
        at a higher rate, we have actionable signal.
        """
        from .smoothness import is_b_smooth

        results = {}
        for rc, pairs in sorted(self.by_regularity.items()):
            if not pairs:
                continue
            smooth_count = sum(
                1 for p in pairs
                if p.sum_mod > 0 and is_b_smooth(p.sum_mod, smoothness_bound)
            )
            results[rc] = smooth_count / len(pairs)
        return results

    def size(self) -> int:
        return len(self.pairs)

    def tier_distribution(self) -> dict[int, int]:
        """Count of pairs per regularity class."""
        return {rc: len(pairs) for rc, pairs in sorted(self.by_regularity.items())}
