"""Corpus of known mathematical cuneiform tablets.

Database of transcribed tablets with their interpretations,
CUNEIFORM representations, and verification results.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from fractions import Fraction

from cuneiform.core.sexagesimal import Sexa
from .tablet_analyzer import TabletAnalyzer


@dataclass
class TabletEntry:
    """A single tablet in the corpus."""
    name: str
    museum_number: str
    provenance: str
    period: str
    description: str
    data: list[list[Sexa]]
    scholarly_interpretation: str
    references: list[str] = field(default_factory=list)

    @property
    def analyzer(self) -> TabletAnalyzer:
        return TabletAnalyzer(self.data)

    def verify(self) -> dict:
        """Run CUNEIFORM verification on this tablet.

        Check: do the calculations work out in exact sexagesimal?
        """
        analyzer = self.analyzer
        relationships = analyzer.identify_column_relationships()
        corrections = analyzer.suggest_corrections()
        regularity = analyzer.check_regularity()
        tablet_type = analyzer.classify_tablet_type()

        return {
            "name": self.name,
            "museum_number": self.museum_number,
            "relationships_found": len(relationships),
            "relationships": relationships,
            "suggested_corrections": corrections,
            "irregular_entries": regularity,
            "classified_type": tablet_type,
            "verified": len(corrections) == 0,
        }


class TabletCorpus:
    """Collection of known mathematical cuneiform tablets.

    Sources:
    - Neugebauer & Sachs, "Mathematical Cuneiform Texts" (1945)
    - Friberg, various publications
    - Mansfield & Wildberger, Historia Mathematica 44(4), 2017
    """

    def __init__(self):
        self.tablets: dict[str, TabletEntry] = {}

    def add(self, entry: TabletEntry):
        self.tablets[entry.name] = entry

    def get(self, name: str) -> TabletEntry | None:
        return self.tablets.get(name)

    def load_known_tablets(self):
        """Load all known mathematical tablets into the corpus."""
        self._load_plimpton322()
        self._load_ybc7289()
        self._load_reciprocal_table()
        self._load_multiplication_table()
        self._load_si427()
        self._load_im67118()
        self._load_ybc11120()

    def verify_all(self) -> dict[str, dict]:
        """Verify every tablet in the corpus."""
        return {name: entry.verify() for name, entry in self.tablets.items()}

    def search_by_type(self, tablet_type: str) -> list[TabletEntry]:
        """Find tablets of a given type."""
        return [
            entry for entry in self.tablets.values()
            if entry.analyzer.classify_tablet_type() == tablet_type
        ]

    def _load_plimpton322(self):
        """Plimpton 322 — the world's oldest trigonometric table.

        Columbia University, c. 1800 BCE.
        15 rows of Pythagorean triples generated from reciprocal pairs.
        Columns: (d/l)², width, diagonal, row number.

        We store width and diagonal (Columns II and III).
        Known scribal errors in rows 2, 9, 13, 15.
        """
        # (width, diagonal) for the 15 rows — corrected values
        plimpton_data = [
            (119, 169),
            (3367, 4825),
            (4601, 6649),
            (12709, 18541),
            (65, 97),
            (319, 481),
            (2291, 3541),
            (799, 1249),
            (481, 769),
            (4961, 8161),
            (45, 75),
            (1679, 2929),
            (161, 289),
            (1771, 3229),
            (56, 106),
        ]

        data = []
        for i, (w, d) in enumerate(plimpton_data):
            # Compute length = sqrt(d² - w²)
            l_sq = d * d - w * w
            l = _isqrt(l_sq)
            # Column I: (d/l)²
            col1 = Fraction(d * d, l * l) if l else Fraction(0)
            data.append([Sexa(col1), Sexa(w), Sexa(d), Sexa(i + 1)])

        self.add(TabletEntry(
            name="Plimpton 322",
            museum_number="Plimpton 322",
            provenance="Larsa (modern Tell as-Senkereh), Iraq",
            period="Old Babylonian (c. 1800 BCE)",
            description=(
                "Table of 15 Pythagorean triples generated by reciprocal pair method. "
                "Columns: (d/l)², width (short side), diagonal (hypotenuse), row number. "
                "The world's oldest trigonometric table."
            ),
            data=data,
            scholarly_interpretation=(
                "Mansfield & Wildberger (2017): an exact sexagesimal trigonometric table, "
                "sorted by decreasing spread. Each row corresponds to a right triangle "
                "whose sides are generated from 5-smooth reciprocal pairs."
            ),
            references=[
                "Neugebauer & Sachs, 'Mathematical Cuneiform Texts' (1945)",
                "Mansfield & Wildberger, Historia Mathematica 44(4), 395-419 (2017)",
                "Robson, 'Neither Sherlock Holmes nor Babylon' (2001)",
            ],
        ))

    def _load_ybc7289(self):
        """YBC 7289 — the √2 approximation tablet.

        Yale Babylonian Collection, c. 1800-1600 BCE.
        A square with diagonal, showing √2 ≈ 1;24,51,10 in base 60.
        """
        # The tablet shows a square with side 30
        # Diagonal annotation: 1;24,51,10 (approximation of √2)
        # Diagonal value: 42;25,35 (= 30 × 1;24,51,10)
        sqrt2_approx = Sexa("1;24,51,10")  # = 1 + 24/60 + 51/3600 + 10/216000
        side = Sexa(30)
        diagonal = side * sqrt2_approx

        data = [
            [side, sqrt2_approx, diagonal],
        ]

        self.add(TabletEntry(
            name="YBC 7289",
            museum_number="YBC 7289",
            provenance="Unknown (southern Iraq)",
            period="Old Babylonian (c. 1800-1600 BCE)",
            description=(
                "Square tablet with side length 30, showing the diagonal calculation "
                "using the approximation √2 ≈ 1;24,51,10. One of the best known "
                "demonstrations of Babylonian mathematical sophistication."
            ),
            data=data,
            scholarly_interpretation=(
                "Demonstrates that OB scribes knew √2 to great accuracy. "
                "The value 1;24,51,10 = 30547/21600 ≈ 1.41421296... "
                "vs actual √2 ≈ 1.41421356... (error < 0.00005%)."
            ),
            references=[
                "Fowler & Robson, 'Square Root Approximations in OB Mathematics' (1998)",
            ],
        ))

    def _load_reciprocal_table(self):
        """Standard OB reciprocal table — the scribal school workhorse.

        Every OB mathematical education included memorizing reciprocal
        pairs: n × (1/n) = 1;0 (= 60) or sometimes 1.
        """
        # Standard reciprocal pairs (n, 60/n) for regular n up to 81
        pairs = [
            (2, 30), (3, 20), (4, 15), (5, 12), (6, 10),
            (8, Fraction(15, 2)), (9, Fraction(20, 3)),
            (10, 6), (12, 5), (15, 4), (16, Fraction(15, 4)),
            (18, Fraction(10, 3)), (20, 3), (24, Fraction(5, 2)),
            (25, Fraction(12, 5)), (27, Fraction(20, 9)),
            (30, 2), (32, Fraction(15, 8)), (36, Fraction(5, 3)),
            (40, Fraction(3, 2)), (45, Fraction(4, 3)),
            (48, Fraction(5, 4)), (50, Fraction(6, 5)),
            (54, Fraction(10, 9)), (60, 1),
        ]

        data = []
        for n, recip in pairs:
            data.append([Sexa(n), Sexa(Fraction(recip) if not isinstance(recip, Fraction) else recip)])

        self.add(TabletEntry(
            name="Standard Reciprocal Table",
            museum_number="composite",
            provenance="Various OB scribal schools",
            period="Old Babylonian (c. 2000-1600 BCE)",
            description=(
                "Standard table of reciprocal pairs for regular (5-smooth) numbers. "
                "The foundation of all OB computational procedures."
            ),
            data=data,
            scholarly_interpretation=(
                "Reciprocal tables were the multiplication tables of Mesopotamia. "
                "Every scribal school student memorized these pairs. Division was "
                "always performed as multiplication by the reciprocal."
            ),
            references=[
                "Neugebauer, 'The Exact Sciences in Antiquity' (1957)",
            ],
        ))

    def _load_multiplication_table(self):
        """Example OB multiplication table (× 9)."""
        data = []
        for i in range(1, 13):
            data.append([Sexa(i), Sexa(9), Sexa(i * 9)])

        self.add(TabletEntry(
            name="Multiplication Table (×9)",
            museum_number="composite",
            provenance="Various OB scribal schools",
            period="Old Babylonian (c. 2000-1600 BCE)",
            description="Multiplication table for 9. Format: n, 9, n×9.",
            data=data,
            scholarly_interpretation=(
                "Standard school exercise tablet. Students practiced "
                "multiplication tables for all regular numbers."
            ),
            references=[
                "Robson, 'Mathematics in Ancient Iraq' (2008)",
            ],
        ))

    def _load_si427(self):
        """Si.427 — Old Babylonian applied geometry (field survey).

        Sippar, c. 1900-1600 BCE. Identified by Mansfield (2021) as the
        oldest known example of applied geometry: a surveyor's cadastral
        tablet that lays out perpendicular field boundaries using Pythagorean
        ("diagonal") triples. Three triples underlie its perpendicular
        constructions: (3, 4, 5), (8, 15, 17), (5, 12, 13).

        Columns: short side, long side, diagonal — so each row is a right
        triangle satisfying a² + b² = c².
        """
        triples = [(3, 4, 5), (8, 15, 17), (5, 12, 13)]
        data = [[Sexa(a), Sexa(b), Sexa(c)] for a, b, c in triples]

        self.add(TabletEntry(
            name="Si.427",
            museum_number="Si.427 (Istanbul Archaeological Museums)",
            provenance="Sippar (modern Abu Habbah), Iraq",
            period="Old Babylonian (c. 1900-1600 BCE)",
            description=(
                "Cadastral (field-survey) tablet laying out perpendicular land "
                "boundaries with Pythagorean triples (3,4,5), (8,15,17), "
                "(5,12,13). Columns: short side, long side, diagonal."
            ),
            data=data,
            scholarly_interpretation=(
                "Mansfield (2021): the oldest known example of applied "
                "geometry. Surveyors used diagonal (Pythagorean) triples with "
                "regular sexagesimal reciprocals to construct accurate right "
                "angles for property boundaries, over a millennium before "
                "Pythagoras."
            ),
            references=[
                "Mansfield, 'Plimpton 322: A Study of Rectangles', "
                "Foundations of Science 26, 977-1005 (2021)",
                "Mansfield & Wildberger, 'Perpendicular Lines and Diagonal "
                "Triples in Old Babylonian Surveying', JCS 72 (2020)",
            ],
        ))

    def _load_im67118(self):
        """IM 67118 (Db2-146) — the completing-the-square rectangle problem.

        Tell edh-Dhiba'i (Eshnunna), c. 1770 BCE, Iraq Museum. A worked
        problem: given a rectangle of area 0;45 (=3/4) and diagonal 1;15
        (=5/4), find the sides. The scribe solves for width 0;45 (=3/4) and
        length 1;0 (=1) by completing the square, then verifies with the
        Pythagorean relation — one of the clearest surviving demonstrations
        that OB scribes used the "Pythagorean" rule in practice.

        Row: width, length, diagonal (a scaled 3-4-5 triple: 3/4, 1, 5/4).
        """
        width = Sexa(Fraction(3, 4))
        length = Sexa(1)
        diagonal = Sexa(Fraction(5, 4))
        data = [[width, length, diagonal]]

        self.add(TabletEntry(
            name="IM 67118",
            museum_number="IM 67118 (= Db2-146), Iraq Museum",
            provenance="Tell edh-Dhiba'i (Eshnunna), near Baghdad, Iraq",
            period="Old Babylonian (c. 1770 BCE)",
            description=(
                "Worked geometry problem: a rectangle with area 0;45 (=3/4) "
                "and diagonal 1;15 (=5/4). Solved for width 0;45 (=3/4) and "
                "length 1;0 (=1) — a 3-4-5 right triangle scaled by 1/4. "
                "Row: width, length, diagonal."
            ),
            data=data,
            scholarly_interpretation=(
                "Høyrup (2002): the solution is cut-and-paste 'naive geometry' "
                "(completing the square), closed by an explicit check with the "
                "Pythagorean relation. Demonstrates OB command of the "
                "Pythagorean theorem c. 1770 BCE, centuries before Plimpton 322 "
                "is usually dated."
            ),
            references=[
                "Baqir, 'Tell Dhiba'i: New Mathematical Texts', Sumer 18 (1962)",
                "Høyrup, 'Lengths, Widths, Surfaces' (2002)",
            ],
        ))

    def _load_ybc11120(self):
        """YBC 11120 — area of a circle from its circumference.

        Yale Babylonian Collection, Old Babylonian. Given circumference
        1;30 (=3/2), the scribe squares it to 2;15 (=9/4) and multiplies by
        the standard constant 0;05 (=1/12) to get the area 0;11,15 (=3/16).
        The constant 1/12 = 1/(4*3) encodes the working value pi = 3.

        Row: circumference, circumference squared, area — so the analyzer
        sees col1 = col0^2 (squaring) and col2/col1 = 1/12 (constant ratio).
        Note: this tablet uses pi = 3; the sharper value 3;7,30 (= 25/8)
        appears on the Susa tablets, and matches ideas/pi.py's historical
        constant.
        """
        circumference = Sexa(Fraction(3, 2))
        circ_squared = Sexa(Fraction(9, 4))
        area = Sexa(Fraction(3, 16))
        data = [[circumference, circ_squared, area]]

        self.add(TabletEntry(
            name="YBC 11120",
            museum_number="YBC 11120",
            provenance="Unknown (southern Iraq)",
            period="Old Babylonian (c. 1800-1600 BCE)",
            description=(
                "Circle area from circumference: C = 1;30 (=3/2), C^2 = 2;15 "
                "(=9/4), area = 0;05 * C^2 = 0;11,15 (=3/16). The constant "
                "0;05 = 1/12 implies pi = 3. Row: C, C^2, area."
            ),
            data=data,
            scholarly_interpretation=(
                "Shows OB scribes extending square/rectangle area methods to "
                "curved figures by inserting a constant (0;05 = 1/(4*pi) with "
                "pi = 3). The refined pi = 3;7,30 of the Susa tablets shows they "
                "knew 3 was only an approximation."
            ),
            references=[
                "Neugebauer & Sachs, 'Mathematical Cuneiform Texts' (1945)",
                "Robson, 'Mathematics in Ancient Iraq' (2008)",
            ],
        ))

    def __len__(self) -> int:
        return len(self.tablets)

    def __repr__(self) -> str:
        return f"TabletCorpus({len(self.tablets)} tablets)"


def _isqrt(n: int) -> int | None:
    """Integer square root if perfect square, else None."""
    if n < 0:
        return None
    if n == 0:
        return 0
    x = n
    y = (x + 1) // 2
    while y < x:
        x = y
        y = (x + n // x) // 2
    return x if x * x == n else None
